### ISSUE TITLE
PYTHON_SITE_PACKAGES_DIR is not honored

### ISSUE THREAD

**Issue by ForceFaction** [Ultimaker/libArcus#110]
This variable does not get used and results in cmake trying to install to a location where the build user doesn't have permissions to copy to.

CMake states that it ignores this variable so it's at least expected that it doesn't work, but the docs state it should work, so either the docs are wrong or this is a bug.

**Comment by ForceFaction** [comment]
commit 12697230b300a9e51f77753f35198d2597eea018 seems to have removed that option from the CMakeLists.txt.

**Comment by Ghostkeeper** [comment]
Yup, you're right. It seems that functionality was removed then to fix an issue with the CMake version we're running on our CentOS build server. I'll remove it from the documentation.

**Comment by ForceFaction** [comment]
That's unfortunate. I'm trying to package this library for Guix and i get a permission denied error because the package tries to install files outside of it's CMAKE_INSTALL_PREFIX'ed path. Build log is attached. If you have questions regarding the build log and what different things mean, please ask :-)

[log.txt](https://github.com/Ultimaker/libArcus/files/5271840/log.txt)

**Comment by Ghostkeeper** [comment]
Hmm, yeah I guess that could happen due to the installation directive at https://github.com/Ultimaker/libArcus/blob/3925125768bac03fafd9b51dceeae2ca1de0f37f/cmake/SIPMacros.cmake#L131

Could you try adjusting `Python3_SITEARCH`?

**Comment by ForceFaction** [comment]
Setting this variable with -DPython3_SITEARCH doesn't make a difference. Even hardcoding doesn't seem to help.

**Comment by ForceFaction** [comment]
I see, no wonder it doesn't work i'm using CMake 3.16 that means the line you mentioned doesn't get executed here, so changes there make no sense.

**Comment by ForceFaction** [comment]
I tried the master and the following worked: 

```
diff --git a/cmake/FindSIP.cmake b/cmake/FindSIP.cmake
index b93873f..238efe1 100644
--- a/cmake/FindSIP.cmake
+++ b/cmake/FindSIP.cmake
@@ -56,7 +56,8 @@ execute_process(
    OUTPUT_STRIP_TRAILING_WHITESPACE
 )
 if(${_process_status} EQUAL 0)
-   string(STRIP ${_process_output} Python3_SITEARCH)
+   set(Python3_SITEARCH "" CACHE STRING "Override")
+   #string(STRIP ${_process_output} Python3_SITEARCH)
 else()
    message(FATAL_ERROR "Failed to get Python3_SITEARCH. Error: ${_process_output}")
 endif()

```

Maybe something similar to this could be added?

**Comment by ForceFaction** [comment]
@Ghostkeeper Is it possible this way? Or does it imply annoying side effects? If not it would be nice if this was added :)

**Comment by Ghostkeeper** [comment]
I think changing `Python3_SITEARCH` somewhere in the FindSIP script can have bad side effects: If another script uses `Python3_SITEARCH` it'll get a different directory based on whether this FindSIP script was executed before or after. So then maybe it's going to install some Python modules in one place, and other Python modules in another.

It also doesn't address the underlying problem that your `Python3_SITEARCH` was apparently incorrect or undesirable. This variable is the output of the [FindPython3](https://cmake.org/cmake/help/v3.12/module/FindPython3.html) script so I don't know if you're really supposed to change it. It would be better to change the inputs of that script, e.g. `Python3_ROOT_DIR`, if you have an alternative location where Python3 is installed.

Only we've since reverted to using [FindPythonInterp](https://cmake.org/cmake/help/latest/module/FindPythonInterp.html) since that worked better with our build servers which are using a rather old version of CMake (3.6).

**Comment by ForceFaction** [comment]
I see. Your argument makes perfect sense and i agree.

I will search how to influence FIndPython3 then.

Thank you for your time :)
