### ISSUE TITLE
mingw32-make Error

### ISSUE THREAD

**Issue by easonyuexcellent** [Ultimaker/libArcus#25]
CMakeFiles\Arcus.dir/objects.a(MessageTypeStore.cpp.obj):MessageTypeStore.cpp:(.text$_ZN9__gnu_cxx13new_allocatorIN6google8protobuf8compiler8ImporterEE7destroyIS4_EEvPT_[_ZN9__gnu_cxx13new_allocatorIN6google8protobuf8compiler8ImporterEE7destroyIS4_EEvPT_]+0x18): undefined reference to `google::protobuf::compiler::Importer::~Importer()'
CMakeFiles\Arcus.dir/objects.a(MessageTypeStore.cpp.obj):MessageTypeStore.cpp:(.rdata$.refptr._ZTVN6google8protobuf8compiler23MultiFileErrorCollectorE[.refptr._ZTVN6google8protobuf8compiler23MultiFileErrorCollectorE]+0x0): undefined reference to `vtable for google::protobuf::compiler::MultiFileErrorCollector'
collect2.exe: error: ld returned 1 exit status
CMakeFiles\Arcus.dir\build.make:205: recipe for target 'libArcus.dll' failed
mingw32-make[2]: *** [libArcus.dll] Error 1
CMakeFiles\Makefile2:66: recipe for target 'CMakeFiles/Arcus.dir/all' failed
mingw32-make[1]: *** [CMakeFiles/Arcus.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
mingw32-make: *** [all] Error 2

**Comment by Ghostkeeper** [comment]
Hmm, a linker error. It compiled libArcus successfully but then couldn't link it up with Protobuf.

Did you compile Protobuf yourself? Did you compile it with the same compiler as you're compiling libArcus with?

**Comment by easonyuexcellent** [comment]
Yup. I use nmake for both libArcus and Protobuf.

**Comment by easonyuexcellent** [comment]
and it shows these errors:

LINK : warning LNK4098: defaultlib 'LIBCMT' conflicts with use of other libs; use /NODEFAULTLIB:library
Arcus.dll : fatal error LNK1169: one or more multiply defined symbols found
LINK failed. with 1169
NMAKE : fatal error U1077: '"C:\Program Files (x86)\CMake\bin\cmake.exe"' : return code '0xffffffff'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\nmake.exe"' : return code '0x2'
Stop.

**Comment by easonyuexcellent** [comment]
Then I changed the compiler into mingw

**Comment by Ghostkeeper** [comment]
Jum. More linker errors!

It's hard to tell since I'm not very experienced with MSVC linker errors. At least one of your errors seems to be [this one](https://msdn.microsoft.com/library/jj889284.aspx), which indicates that the two pieces weren't compiled with the same settings. In this case, it seems that Protobuf was compiled to link dynamically with your C runtime library, but libArcus was compiled to link dynamically with your C runtime library. Apparently that's a problem. I don't know about any CMake settings you could change to mend this. All I get when I search online is to "change your compiler settings" to either statically or dynamically link both projects.

All the LNK2005 errors seem to be caused by the LNK2038 errors.

Ultimaker runs most of its Windows builds with MinGW-w64, by the way. Only for the Python binaries we still need to use MSVC since Python bindings need to be compiled with the same compiler as Python itself.

**Comment by easonyuexcellent** [comment]
Thaks, this problem was on win10 vs2015. I will try on win7 vs2008.
