### ISSUE TITLE
Use "stable" protobuf.

### ISSUE THREAD

**Issue by Equidamoid** [Ultimaker/libArcus#8]
The library can't be built using protobuf version that is present in repositories:
```example.protoexample.proto::1:101: :Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".10:
Unrecognized syntax identifier "proto3".  This parser only recognizes "proto2".```
Use of proto3 requires manual build of protobuf beta version that is veeeery unconvinient.

**Comment by Ghostkeeper** [comment]
Ultimaker has its own fork of Protobuf, [here](https://github.com/Ultimaker/protobuf). We've made a CMake list for it, so it should be fairly easy to build (as opposed to building with Autotools). If you have CMake and a compiler, it should be as easy as calling "cmake .." from a build directory and then running "make install".

The reason we're using that version is because we're using some of the features in Protobuf 3, such as proper JSON. It made development much easier and makes Cura better in the long run. We haven't found any bugs with it yet apart from some things that made it hard to build. Protobuf has added a CMake list themselves in the meanwhile, too. Let's hope they go out of beta soon.

**Comment by Equidamoid** [comment]
> as opposed to building with Autotools
What's wrong with autotools?
Autotools is ok (until you need to modify the scripts). The dependency to be installed manually + all this magic spells to make cmake use that protobuf installed to some prefix -- this is not ok. It is not critical but quite annoying.

**Comment by awhiemstra** [comment]
We cannot use stable protobuf due to the lack of python 3 bindings.

"What's wrong with autotools?"

For starters, that it is an incredible pain to use on Windows.
